CREATE TABLE tbl_user (
	id BIGINT(10) NOT NULL AUTO_INCREMENT,
	password VARCHAR(255) NOT NULL DEFAULT '' COLLATE 'utf8mb4_unicode_ci',	
	firstname VARCHAR(60) NOT NULL DEFAULT '' COLLATE 'utf8mb4_unicode_ci',
	lastname VARCHAR(60) NOT NULL DEFAULT '' COLLATE 'utf8mb4_unicode_ci',
	email VARCHAR(60) NOT NULL DEFAULT '' UNIQUE COLLATE 'utf8mb4_unicode_ci',
	timecreate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,	
	PRIMARY KEY (id) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
ROW_FORMAT=COMPRESSED
AUTO_INCREMENT=0;



CREATE TABLE tbl_role (
	id BIGINT(10) NOT NULL AUTO_INCREMENT,
	name VARCHAR(60) NOT NULL DEFAULT '' UNIQUE COLLATE 'utf8mb4_unicode_ci',
	timecreate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,	
	PRIMARY KEY (id) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
ROW_FORMAT=COMPRESSED
AUTO_INCREMENT=0;




CREATE TABLE tbl_user_role (
	user_id BIGINT(10) NOT NULL,
	role_id BIGINT(10) NOT NULL,
	timecreate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (user_id, role_id),
	FOREIGN KEY (user_id) REFERENCES tbl_user(id),
	FOREIGN KEY (role_id) REFERENCES tbl_role(id)
)
ENGINE=InnoDB
ROW_FORMAT=COMPRESSED;
